### ISSUE TITLE
if the Project had an Example end to end would help a lot

### ISSUE THREAD

**Issue by deresegetachew** [alawong/react-native-braintree#7]
HI there;

First thank you for your awesome work; i have managed to follow the instructions and use the braintree and it opens this new blank page and its forever loading; if you happen to have the time please include an example in the project i am not quite sure how things work and  what to expect once i make the call too.
BTClient.showPaymentViewController(function(err, nonce) {
  //payment succeeded, pass nonce to server
});

an example would really go a long way in helping us out 

Thank you

**Comment by alanhhwong** [comment]
@derese just added a full end to end sample with client + server integration: https://github.com/alawong/BTRNSample

Also updated readme with link to sample.

**Comment by deresegetachew** [comment]
Thank you!
