### ISSUE TITLE
RNBraintree.showPayPalViewController() not found

### ISSUE THREAD

**Issue by deresegetachew** [alawong/react-native-braintree#8]
I am running in to this error when use try out paypal only
![simulator screen shot jan 22 2016 4 06 40 pm](https://cloud.githubusercontent.com/assets/2713659/12511468/94959c82-c122-11e5-94ea-60f59d7097a2.png)

**Comment by alanhhwong** [comment]
@derese can you try and cross-check with the new sample?  Hard to tell where the error is just from the screen.

**Comment by sayhei** [comment]
i have this issues too .I did the same, and it happened sometimes.

**Comment by sayhei** [comment]
After I finish the payment, it jumps to the red interface.

**Comment by XiSmartElf** [comment]
I am facing the same issue. RNBraintree is undefined. This is happening in the library

var RNBraintree = require('react-native').NativeModules.RNBraintree;

Please reopen this issue
