### ISSUE TITLE
Duplicated symbols when compiling in release

### ISSUE THREAD

**Issue by alvaromb** [alawong/react-native-braintree#9]
When compiling and archiving an app for a TestFlight release, I get duplicated symbols error: 

```
❌  duplicate symbol _RCTReactTagAttributeName in
> libReact.a(RCTShadowText.o)
> libRCTText.a(RCTShadowText.o)
[14:22:23]: Exit status: 65
```

I have to manually remove `*.a` from **Link Binary With Libraries** in order to make it work. However, when running into the simulator, I have to re-add those libraries because I get this error:

```
2016-01-25 14:32:01.342 [info][tid:com.facebook.React.JavaScript] Unable to load source map: RCTNetworking module is not available
```

**Comment by alanhhwong** [comment]
@alvaromb yeah that's due to having duplicate copies for React Native.  I removed all libraries except libPods.a under `Link Binary With Libraries` and it works fine in simulator..
